package dev.codespire.orchestrator.work;

import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.node.ObjectNode;
import dev.codespire.contract.work.WorkPreparation;
import dev.codespire.worksource.WorkTicket;
import jakarta.enterprise.context.ApplicationScoped;
import jakarta.inject.Inject;

/**
 * The two texts a prepared task needs, composed from the one ticket a person wrote (M3.5 part C).
 *
 * <p>Nothing here is generated by a model: M4 owns that. This is the bridge that removes the typing —
 * the operator's own ticket becomes the specification, and the plan is the single step the schema
 * already requires, naming that specification by digest. The rules it must satisfy are the ones
 * {@code WorkArtifacts.observe} enforces, so a composed plan is validated by exactly the same code that
 * validates one a person pasted into a ticket.
 */
@ApplicationScoped
public class WorkPreparationComposer {
    @Inject ObjectMapper mapper;

    /** What {@code WorkArtifacts.observe} accepts today; the composer writes that shape, not its own. */
    static final int PLAN_SCHEMA_VERSION = 1;

    /** The bound the tracker read already applies, so a composed text cannot exceed what can be re-read. */
    static final int MAX_BODY_CHARS = 48 * 1024;

    /** Why a ticket cannot become a specification. Each one is a sentence on the item's own page. */
    public static final class NotComposable extends RuntimeException {
        private final String reason;
        NotComposable(String reason) { super(reason); this.reason = reason; }
        public String reason() { return reason; }
    }

    /**
     * The specification: the ticket's title and body, exactly as the person wrote them.
     *
     * <p>The title is included because a ticket body often continues from it ("...as described above"),
     * and because the agent is told to implement this text and nothing else.
     */
    public String specification(WorkTicket ticket) {
        String title = ticket.title() == null ? "" : ticket.title().trim();
        String body = ticket.body() == null ? "" : ticket.body().strip();
        if (body.isEmpty()) throw new NotComposable("ticket_body_empty");
        String composed = title.isEmpty() ? body : title + "\n\n" + body;
        if (composed.length() > MAX_BODY_CHARS) throw new NotComposable("ticket_body_too_large");
        return composed;
    }

    /**
     * The plan: one step, naming the specification version it was composed from.
     *
     * <p>The instruction does not repeat the specification. The dispatch prompt already carries both
     * texts ({@code WorkRunAssembly.parse}), so repeating it would send the ticket twice and pay for it
     * twice.
     */
    public String plan(String specification) {
        ObjectNode plan = mapper.createObjectNode();
        plan.put("schemaVersion", PLAN_SCHEMA_VERSION);
        plan.put("specificationSha256", WorkPreparation.digest(specification));
        ObjectNode step = plan.putArray("steps").addObject();
        step.put("id", "step-1");
        step.put("instruction", "Implement the specification in full, and change nothing it does not ask for.");
        try { return mapper.writerWithDefaultPrettyPrinter().writeValueAsString(plan); }
        catch (com.fasterxml.jackson.core.JsonProcessingException impossible) {
            throw new IllegalStateException("Cannot write a composed plan", impossible);
        }
    }
}
